In [ ]:
import pandas as pd

In [ ]:
import duckdb

In [ ]:
conditions = pd.read_json("/content/drive/MyDrive/Disease_engine_project/release_conditions.json")

In [ ]:
con_names = conditions.columns

In [ ]:
conn = duckdb.connect()

In [ ]:
feature_df = pd.read_csv("/content/drive/MyDrive/Disease_engine_project/processed_data/features.csv")

In [ ]:
query = "SELECT * FROM '/content/drive/MyDrive/Disease_engine_project/processed_data/output_*.parquet' WHERE Diagnosis = \'"
## SQL query to pull the data from the specified disease across all the parquets
averages_df = feature_df.iloc[:,:].drop(columns=["Age"])

for i in con_names:
  ## Get averaged vectors (centroids) for each condition
  condition_df = conn.execute(query + i + "\'").df().drop(columns=["Diagnosis", "Age"])
  avg_row = {}
  avg_row["Diagnosis"] = [i]
  for j in condition_df:
    avg_row[j] = [condition_df[j].mean()] ## Get average for evidence
  avg_row = pd.DataFrame(avg_row)
  averages_df = pd.concat([averages_df, avg_row], ignore_index=True)

averages_df.to_parquet("/content/drive/MyDrive/Disease_engine_project/processed_data/output_average.parquet", engine='pyarrow')

In [ ]:
averages_df.tail()

,Diagnosis,E_91,E_55_V_123,E_55_V_14,E_55_V_15,E_55_V_16,E_55_V_17,E_55_V_18,E_55_V_19,E_55_V_20,...,E_200,E_199,E_121,E_120,E_142,E_195,E_183,E_224,E_223,E_5
44,Possible NSTEMI / STEMI,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
45,Sarcoidosis,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
46,Pancreatic neoplasm,0.0,0.027327,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.749018,0.000000
47,Acute pulmonary edema,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.826901
48,Pericarditis,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000

In [ ]:
## This cell does the same as the one above but for the data containing the signed encoding
query = "SELECT * FROM '/content/drive/MyDrive/Disease_engine_new_encoding/processed_data/output_*.parquet' WHERE Diagnosis = \'"
## SQL query to pull the data from the specified disease across all the parquets
averages_df = feature_df.iloc[:,:].drop(columns=["Age"])

for i in con_names:
  ## Get averaged vectors (centroids) for each condition
  condition_df = conn.execute(query + i + "\'").df().drop(columns=["Diagnosis", "Age"])
  avg_row = {}
  avg_row["Diagnosis"] = [i]
  for j in condition_df:
    avg_row[j] = [condition_df[j].mean()] ## Get average for evidence
  avg_row = pd.DataFrame(avg_row)
  averages_df = pd.concat([averages_df, avg_row], ignore_index=True)

averages_df.to_parquet("/content/drive/MyDrive/Disease_engine_new_encoding/processed_data/output_average.parquet", engine='pyarrow')

With this cell, all centroids are computed and stored

In [ ]:
averages_df.tail()

,Diagnosis,E_91,E_55_V_123,E_55_V_14,E_55_V_15,E_55_V_16,E_55_V_17,E_55_V_18,E_55_V_19,E_55_V_20,...,E_200,E_199,E_121,E_120,E_142,E_195,E_183,E_224,E_223,E_5
44,Possible NSTEMI / STEMI,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000
45,Sarcoidosis,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000
46,Pancreatic neoplasm,-1.0,-0.956044,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.472527,-1.000000
47,Acute pulmonary edema,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,0.597884
48,Pericarditis,-1.0,-1.000000,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000