When a person states their symptoms, stating whether a symptom is present or not, the system will recommend a series of extra questions, evidences that in case of being true or false will contribute to the system diagnosing a person. Such recommendation of questions will be based on the features with no registered answer (set to zero) that would either affirm the diagnosis or reject it and point toward another diagnosis.

The recommendation system is based on the algrebraic difference between on each index comparing both patient vector and diagnosis profile vector

In [ ]:
import pandas as pd
import numpy as np
import json
from google import genai

In [ ]:
client = genai.Client(api_key = "Super secret key")

In [ ]:
all_features = pd.read_json("/content/drive/MyDrive/Disease_engine_project/release_evidences.json")

In [ ]:
all_features = all_features.T

In [ ]:
all_features = all_features.drop(columns = ["code_question", "question_fr"])

In [ ]:
all_features = all_features.reset_index(drop=True)

In [ ]:
all_features = all_features.drop(columns = ["is_antecedent"])

The following section formats the questions in a way that can be better understood by the LLM by matching a question with its answer

In [ ]:
binary = all_features[all_features["data_type"] == "B"]

In [ ]:
multiple_choice = all_features[all_features["data_type"] == "M"]

In [ ]:
single_choice = all_features[all_features["data_type"] == "C"]

In [ ]:
type(single_choice.iloc[0]["value_meaning"])

dict

In [ ]:
row_list=[]
for i in range(0, single_choice.shape[0]):
  row = single_choice.iloc[i]
  main_name = row["name"]
  main_question = row["question_en"]
  new_row = {}
  for j in row["possible-values"]:
    new_row = {}
    row_name = main_name
    row_question = main_question
    row_name = row_name + "_" + str(j)
    if row["default_value"] == 0:
      row_question = row_question + " - Answer: " + str(j)
    else:
      row_question = row_question + " - Answer: " + str(row["value_meaning"][j]["en"])
    new_row["code"] = row_name
    new_row["question"] = row_question
    new_row["value"] = 0
    new_row["type"] = 'C'
    row_list.append(new_row)

In [ ]:
for i in range(0, multiple_choice.shape[0]):
  row = multiple_choice.iloc[i]
  main_name = row["name"]
  main_question = row["question_en"]
  new_row = {}
  for j in row["possible-values"]:
    new_row = {}
    row_name = main_name
    row_question = main_question
    row_name = row_name + "_" + str(j)
    if row["default_value"] == 0:
      row_question = row_question + " - Answer: " + str(j)
    else:
      row_question = row_question + " - Answer: " + str(row["value_meaning"][j]["en"])
    new_row["code"] = row_name
    new_row["question"] = row_question
    new_row["value"] = 0
    new_row["type"] = 'M'
    row_list.append(new_row)

In [ ]:
binary

,name,question_en,default_value,value_meaning,possible-values,data_type
0,E_91,Do you have a fever (either felt or measured w...,0,{},[],B
2,E_53,"Do you have pain somewhere, related to your re...",0,{},[],B
8,E_159,Did you lose consciousness?,0,{},[],B
10,E_129,"Do you have any lesions, redness or problems o...",0,{},[],B
17,E_154,Is your skin much paler than usual?,0,{},[],B
...,...,...,...,...,...,...
218,E_195,Do you live in the suburbs?,0,{},[],B
219,E_183,Do you live in a rural area?,0,{},[],B
220,E_224,Do you have family members who have had lung c...,0,{},[],B
221,E_223,Are there members of your family who have been...,0,{},[],B
222,E_5,Have you ever had fluid in your lungs?,0,{},[],B

In [ ]:
for i in range(0, binary.shape[0]):
  row = binary.iloc[i]
  main_name = row["name"]
  main_question = row["question_en"]
  new_row = {}
  new_row["code"] = main_name
  new_row["question"] = main_question
  new_row["value"] = 0
  new_row["type"] = 'B'
  row_list.append(new_row)

In [ ]:
pd.DataFrame(row_list).head()

     code                                   question  value
0  E_59_0  How fast did the pain appear? - Answer: 0      0
1  E_59_1  How fast did the pain appear? - Answer: 1      0
2  E_59_2  How fast did the pain appear? - Answer: 2      0
3  E_59_3  How fast did the pain appear? - Answer: 3      0
4  E_59_4  How fast did the pain appear? - Answer: 4      0

In [ ]:
prompt_data = str(row_list)

The following cell sets up "rules" for the LLM to get the desired result

In [ ]:
prompt1 = "The following data has this format: [{\"code\": code, \"question\": question and answer to the question, \"value\": value, \"type\": type}]: "
prompt2 = "Return this list in the same valid JSON format following the set of rules I will state:"
rule_prompt_B = "\nIf a question has its value field set to \'B\': Change the value of the \'value\' field to 1 if the information provides enough evidence for the answer of that question to be yes, change it to -1 if the information provides enough information for the answer to that question to be no, leave it as 0 if there isn't enough evidence for answering such question."
rule_prompt_C = "\nIf a question has its value field set to \'C\': Change the value of the \'value\' field to 1 if the information provides enough evidence for affirming the answer of the given question, change it to -1 if the information provides enough evidence for refuting the answer of the given question, leave it as 0 if there isn't enough evidence for affirming or refuting. Amongst all the questions that share the same code section E_*, and whose type is \'C\', only one option per code (E_*_V_* or E_*_*) can be 1 at the time, that is, setting to 1 an option (E_*_V_* or E_*_*) automatically refutes all the other options that share the same E_* code."
rule_prompt_M = "\nIf a question has its value field set to \'M\': Change the value of the \'value\' field to 1 if the information provides enough evidence for affirming the answer of the given question, change it to -1 if the information provides enough evidence for refuting the answer of the given question, leave it as 0 if there isn't enough evidence for affirming or refuting. Amongst all the questions that share the same code section E_*, and whose type is \'M\', more than one option per code E_*_V_* can be 1 at the same time, that is, setting to 1 an option E_*_V_* does NOT automatically refute all the other options that share the same E_* code, therefore, non explicitly mentioned answers should not be set to -1 unless the user explicitly discards them."
rule_closer = "nOnce done, double check your work to ensure that the product matches the expected format in every single row.\nPrompt: "

In [ ]:
user_prompt = "The pain took its sweet time to appear, and is kinda intense. You know, sure it is my poor diet and antecedents of lung cancer. Nevertheless, that doesn't explain the sharp pain in both of my biceps. But hey, at least I haven't had asthma and both my knees feel excelent."

In [ ]:
response = client.models.generate_content(
    model="gemini-3.1-flash-lite",
    contents=prompt1 + prompt_data + "\n" + prompt2 + rule_prompt_B + rule_prompt_C + rule_prompt_M + rule_closer + user_prompt
)
print(response.text)

```json
[
  {"code": "E_59_0", "question": "How fast did the pain appear? - Answer: 0", "value": -1, "type": "C"},
  {"code": "E_59_1", "question": "How fast did the pain appear? - Answer: 1", "value": -1, "type": "C"},
  {"code": "E_59_2", "question": "How fast did the pain appear? - Answer: 2", "value": -1, "type": "C"},
  {"code": "E_59_3", "question": "How fast did the pain appear? - Answer: 3", "value": -1, "type": "C"},
  {"code": "E_59_4", "question": "How fast did the pain appear? - Answer: 4", "value": -1, "type": "C"},
  {"code": "E_59_5", "question": "How fast did the pain appear? - Answer: 5", "value": -1, "type": "C"},
  {"code": "E_59_6", "question": "How fast did the pain appear? - Answer: 6", "value": -1, "type": "C"},
  {"code": "E_59_7", "question": "How fast did the pain appear? - Answer: 7", "value": -1, "type": "C"},
  {"code": "E_59_8", "question": "How fast did the pain appear? - Answer: 8", "value": -1, "type": "C"},
  {"code": "E_59_9", "question": "How fast did the pain appear? - Answer: 9", "value": -1, "type": "C"},
  {"code": "E_59_10", "question": "How fast did the pain appear? - Answer: 10", "value": 1, "type": "C"},
  {"code": "E_56_0", "question": "How intense is the pain? - Answer: 0", "value": -1, "type": "C"},
  {"code": "E_56_1", "question": "How intense is the pain? - Answer: 1", "value": -1, "type": "C"},
  {"code": "E_56_2", "question": "How intense is the pain? - Answer: 2", "value": -1, "type": "C"},
  {"code": "E_56_3", "question": "How intense is the pain? - Answer: 3", "value": -1, "type": "C"},
  {"code": "E_56_4", "question": "How intense is the pain? - Answer: 4", "value": -1, "type": "C"},
  {"code": "E_56_5", "question": "How intense is the pain? - Answer: 5", "value": -1, "type": "C"},
  {"code": "E_56_6", "question": "How intense is the pain? - Answer: 6", "value": -1, "type": "C"},
  {"code": "E_56_7", "question": "How intense is the pain? - Answer: 7", "value": 1, "type": "C"},
  {"code": "E_56_8", "question": "How intense is the pain? - Answer: 8", "value": -1, "type": "C"},
  {"code": "E_56_9", "question": "How intense is the pain? - Answer: 9", "value": -1, "type": "C"},
  {"code": "E_56_10", "question": "How intense is the pain? - Answer: 10", "value": -1, "type": "C"},
  {"code": "E_58_0", "question": "How precisely is the pain located? - Answer: 0", "value": 0, "type": "C"},
  {"code": "E_58_1", "question": "How precisely is the pain located? - Answer: 1", "value": 0, "type": "C"},
  {"code": "E_58_2", "question": "How precisely is the pain located? - Answer: 2", "value": 0, "type": "C"},
  {"code": "E_58_3", "question": "How precisely is the pain located? - Answer: 3", "value": 0, "type": "C"},
  {"code": "E_58_4", "question": "How precisely is the pain located? - Answer: 4", "value": 0, "type": "C"},
  {"code": "E_58_5", "question": "How precisely is the pain located? - Answer: 5", "value": 0, "type": "C"},
  {"code": "E_58_6", "question": "How precisely is the pain located? - Answer: 6", "value": 0, "type": "C"},
  {"code": "E_58_7", "question": "How precisely is the pain located? - Answer: 7", "value": 0, "type": "C"},
  {"code": "E_58_8", "question": "How precisely is the pain located? - Answer: 8", "value": 0, "type": "C"},
  {"code": "E_58_9", "question": "How precisely is the pain located? - Answer: 9", "value": 0, "type": "C"},
  {"code": "E_58_10", "question": "How precisely is the pain located? - Answer: 10", "value": 0, "type": "C"},
  {"code": "E_130_V_11", "question": "What color is the rash? - Answer: NA", "value": 0, "type": "C"},
  {"code": "E_130_V_86", "question": "What color is the rash? - Answer: dark", "value": 0, "type": "C"},
  {"code": "E_130_V_107", "question": "What color is the rash? - Answer: yellow", "value": 0, "type": "C"},
  {"code": "E_130_V_138", "question": "What color is the rash? - Answer: pale", "value": 0, "type": "C"},
  {"code": "E_130_V_156", "question": "What color is the rash? - Answer: pink", "value": 0, "type": "C"},
  {"code": "E_130_V_157", "question": "What color is the rash? - Answer: red", "value": 0, "type": "C"},
  {"code": "E_134_0", "question": "How intense is the pain caused by the rash? - Answer: 0", "value": 0, "type": "C"},
  {"code": "E_134_1", "question": "How intense is the pain caused by the rash? - Answer: 1", "value": 0, "type": "C"},
  {"code": "E_134_2", "question": "How intense is the pain caused by the rash? - Answer: 2", "value": 0, "type": "C"},
  {"code": "E_134_3", "question": "How intense is the pain caused by the rash? - Answer: 3", "value": 0, "type": "C"},
  {"code": "E_134_4", "question": "How intense is the pain caused by the rash? - Answer: 4", "value": 0, "type": "C"},
  {"code": "E_134_5", "question": "How intense is the pain caused by the rash? - Answer: 5", "value": 0, "type": "C"},
  {"code": "E_134_6", "question": "How intense is the pain caused by the rash? - Answer: 6", "value": 0, "type": "C"},
  {"code": "E_134_7", "question": "How intense is the pain caused by the rash? - Answer: 7", "value": 0, "type": "C"},
  {"code": "E_134_8", "question": "How intense is the pain caused by the rash? - Answer: 8", "value": 0, "type": "C"},
  {"code": "E_134_9", "question": "How intense is the pain caused by the rash? - Answer: 9", "value": 0, "type": "C"},
  {"code": "E_134_10", "question": "How intense is the pain caused by the rash? - Answer: 10", "value": 0, "type": "C"},
  {"code": "E_132_0", "question": "Is the rash swollen? - Answer: 0", "value": 0, "type": "C"},
  {"code": "E_132_1", "question": "Is the rash swollen? - Answer: 1", "value": 0, "type": "C"},
  {"code": "E_132_2", "question": "Is the rash swollen? - Answer: 2", "value": 0, "type": "C"},
  {"code": "E_132_3", "question": "Is the rash swollen? - Answer: 3", "value": 0, "type": "C"},
  {"code": "E_132_4", "question": "Is the rash swollen? - Answer: 4", "value": 0, "type": "C"},
  {"code": "E_132_5", "question": "Is the rash swollen? - Answer: 5", "value": 0, "type": "C"},
  {"code": "E_132_6", "question": "Is the rash swollen? - Answer: 6", "value": 0, "type": "C"},
  {"code": "E_132_7", "question": "Is the rash swollen? - Answer: 7", "value": 0, "type": "C"},
  {"code": "E_132_8", "question": "Is the rash swollen? - Answer: 8", "value": 0, "type": "C"},
  {"code": "E_132_9", "question": "Is the rash swollen? - Answer: 9", "value": 0, "type": "C"},
  {"code": "E_132_10", "question": "Is the rash swollen? - Answer: 10", "value": 0, "type": "C"},
  {"code": "E_136_0", "question": "How severe is the itching? - Answer: 0", "value": 0, "type": "C"},
  {"code": "E_136_1", "question": "How severe is the itching? - Answer: 1", "value": 0, "type": "C"},
  {"code": "E_136_2", "question": "How severe is the itching? - Answer: 2", "value": 0, "type": "C"},
  {"code": "E_136_3", "question": "How severe is the itching? - Answer: 3", "value": 0, "type": "C"},
  {"code": "E_136_4", "question": "How severe is the itching? - Answer: 4", "value": 0, "type": "C"},
  {"code": "E_136_5", "question": "How severe is the itching? - Answer: 5", "value": 0, "type": "C"},
  {"code": "E_136_6", "question": "How severe is the itching? - Answer: 6", "value": 0, "type": "C"},
  {"code": "E_136_7", "question": "How severe is the itching? - Answer: 7", "value": 0, "type": "C"},
  {"code": "E_136_8", "question": "How severe is the itching? - Answer: 8", "value": 0, "type": "C"},
  {"code": "E_136_9", "question": "How severe is the itching? - Answer: 9", "value": 0, "type": "C"},
  {"code": "E_136_10", "question": "How severe is the itching? - Answer: 10", "value": 0, "type": "C"},
  {"code": "E_135_V_10", "question": "Is the lesion (or are the lesions) larger than 1cm? - Answer: N", "value": 0, "type": "C"},
  {"code": "E_135_V_12", "question": "Is the lesion (or are the lesions) larger than 1cm? - Answer: Y", "value": 0, "type": "C"},
  {"code": "E_131_V_10", "question": "Do your lesions peel off? - Answer: N", "value": 0, "type": "C"},
  {"code": "E_131_V_12", "question": "Do your lesions peel off? - Answer: Y", "value": 0, "type": "C"},
  {"code": "E_204_V_10", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: N", "value": 0, "type": "C"},
  {"code": "E_204_V_0", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: North Africa", "value": 0, "type": "C"},
  {"code": "E_204_V_1", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: West Africa", "value": 0, "type": "C"},
  {"code": "E_204_V_2", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: South Africa", "value": 0, "type": "C"},
  {"code": "E_204_V_3", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: Central America", "value": 0, "type": "C"},
  {"code": "E_204_V_4", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: North America", "value": 0, "type": "C"},
  {"code": "E_204_V_5", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: South America", "value": 0, "type": "C"},
  {"code": "E_204_V_6", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: Asia", "value": 0, "type": "C"},
  {"code": "E_204_V_7", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: South East Asia", "value": 0, "type": "C"},
  {"code": "E_204_V_8", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: Caraibes", "value": 0, "type": "C"},
  {"code": "E_204_V_9", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: Europe", "value": 0, "type": "C"},
  {"code": "E_204_V_13", "question": "Have you traveled out of the country in the last 4 weeks? - Answer: Oceania", "value": 0, "type": "C"},
  {"code": "E_55_V_123", "question": "Do you feel pain somewhere? - Answer: nowhere", "value": -1, "type": "M"},
  {"code": "E_55_V_14", "question": "Do you feel pain somewhere? - Answer: iliac wing(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_15", "question": "Do you feel pain somewhere? - Answer: iliac wing(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_16", "question": "Do you feel pain somewhere? - Answer: groin(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_17", "question": "Do you feel pain somewhere? - Answer: groin(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_18", "question": "Do you feel pain somewhere? - Answer: axilla(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_19", "question": "Do you feel pain somewhere? - Answer: axilla(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_20", "question": "Do you feel pain somewhere? - Answer: tonsil(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_21", "question": "Do you feel pain somewhere? - Answer: tonsil(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_22", "question": "Do you feel pain somewhere? - Answer: anus", "value": 0, "type": "M"},
  {"code": "E_55_V_23", "question": "Do you feel pain somewhere? - Answer: posterior aspect of the ankle(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_24", "question": "Do you feel pain somewhere? - Answer: posterior aspect of the ankle(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_25", "question": "Do you feel pain somewhere? - Answer: back of head", "value": 0, "type": "M"},
  {"code": "E_55_V_26", "question": "Do you feel pain somewhere? - Answer: back of the neck", "value": 0, "type": "M"},
  {"code": "E_55_V_27", "question": "Do you feel pain somewhere? - Answer: forearm(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_28", "question": "Do you feel pain somewhere? - Answer: forearm(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_29", "question": "Do you feel pain somewhere? - Answer: lower chest", "value": 0, "type": "M"},
  {"code": "E_55_V_30", "question": "Do you feel pain somewhere? - Answer: biceps(R)", "value": 1, "type": "M"},
  {"code": "E_55_V_31", "question": "Do you feel pain somewhere? - Answer: biceps(L)", "value": 1, "type": "M"},
  {"code": "E_55_V_32", "question": "Do you feel pain somewhere? - Answer: mouth", "value": 0, "type": "M"},
  {"code": "E_55_V_33", "question": "Do you feel pain somewhere? - Answer: thyroid cartilage", "value": 0, "type": "M"},
  {"code": "E_55_V_34", "question": "Do you feel pain somewhere? - Answer: ankle(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_35", "question": "Do you feel pain somewhere? - Answer: ankle(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_36", "question": "Do you feel pain somewhere? - Answer: clitoris", "value": 0, "type": "M"},
  {"code": "E_55_V_37", "question": "Do you feel pain somewhere? - Answer: coccyx", "value": 0, "type": "M"},
  {"code": "E_55_V_38", "question": "Do you feel pain somewhere? - Answer: cervical spine", "value": 0, "type": "M"},
  {"code": "E_55_V_39", "question": "Do you feel pain somewhere? - Answer: thoracic spine", "value": 0, "type": "M"},
  {"code": "E_55_V_40", "question": "Do you feel pain somewhere? - Answer: lumbar spine", "value": 0, "type": "M"},
  {"code": "E_55_V_41", "question": "Do you feel pain somewhere? - Answer: commissure(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_42", "question": "Do you feel pain somewhere? - Answer: commissure(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_43", "question": "Do you feel pain somewhere? - Answer: lateral side of the foot(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_44", "question": "Do you feel pain somewhere? - Answer: lateral side of the foot(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_45", "question": "Do you feel pain somewhere? - Answer: elbow(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_46", "question": "Do you feel pain somewhere? - Answer: elbow(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_47", "question": "Do you feel pain somewhere? - Answer: popliteal fossa(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_48", "question": "Do you feel pain somewhere? - Answer: popliteal fossa(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_49", "question": "Do you feel pain somewhere? - Answer: iliac crest(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_50", "question": "Do you feel pain somewhere? - Answer: iliac crest(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_51", "question": "Do you feel pain somewhere? - Answer: thigh(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_52", "question": "Do you feel pain somewhere? - Answer: thigh(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_53", "question": "Do you feel pain somewhere? - Answer: side of the neck(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_54", "question": "Do you feel pain somewhere? - Answer: side of the neck(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_55", "question": "Do you feel pain somewhere? - Answer: side of the chest(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_56", "question": "Do you feel pain somewhere? - Answer: side of the chest(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_57", "question": "Do you feel pain somewhere? - Answer: lower teeth(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_58", "question": "Do you feel pain somewhere? - Answer: lower teeth(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_59", "question": "Do you feel pain somewhere? - Answer: upper teeth(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_60", "question": "Do you feel pain somewhere? - Answer: upper teeth(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_61", "question": "Do you feel pain somewhere? - Answer: above the tongue", "value": 0, "type": "M"},
  {"code": "E_55_V_62", "question": "Do you feel pain somewhere? - Answer: top of the head", "value": 0, "type": "M"},
  {"code": "E_55_V_63", "question": "Do you feel pain somewhere? - Answer: finger (ring finger)(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_64", "question": "Do you feel pain somewhere? - Answer: finger (ring finger)(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_65", "question": "Do you feel pain somewhere? - Answer: finger (little finger)(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_66", "question": "Do you feel pain somewhere? - Answer: finger (little finger)(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_67", "question": "Do you feel pain somewhere? - Answer: finger (index)(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_68", "question": "Do you feel pain somewhere? - Answer: finger (index)(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_69", "question": "Do you feel pain somewhere? - Answer: finger (middle)(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_70", "question": "Do you feel pain somewhere? - Answer: finger (middle)(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_72", "question": "Do you feel pain somewhere? - Answer: dorsal aspect of the foot(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_73", "question": "Do you feel pain somewhere? - Answer: dorsal aspect of the foot(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_74", "question": "Do you feel pain somewhere? - Answer: dorsal aspect of the wrist(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_75", "question": "Do you feel pain somewhere? - Answer: dorsal aspect of the wrist(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_76", "question": "Do you feel pain somewhere? - Answer: dorsal aspect of the hand(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_77", "question": "Do you feel pain somewhere? - Answer: dorsal aspect of the hand(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_78", "question": "Do you feel pain somewhere? - Answer: palmar side of the forearm(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_79", "question": "Do you feel pain somewhere? - Answer: palmar side of the forearm(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_80", "question": "Do you feel pain somewhere? - Answer: palmar face of the wrist(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_81", "question": "Do you feel pain somewhere? - Answer: palmar face of the wrist(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_82", "question": "Do you feel pain somewhere? - Answer: buttock(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_83", "question": "Do you feel pain somewhere? - Answer: buttock(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_84", "question": "Do you feel pain somewhere? - Answer: flank(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_85", "question": "Do you feel pain somewhere? - Answer: flank(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_87", "question": "Do you feel pain somewhere? - Answer: iliac fossa(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_88", "question": "Do you feel pain somewhere? - Answer: iliac fossa(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_89", "question": "Do you feel pain somewhere? - Answer: forehead", "value": 0, "type": "M"},
  {"code": "E_55_V_90", "question": "Do you feel pain somewhere? - Answer: lower gum", "value": 0, "type": "M"},
  {"code": "E_55_V_91", "question": "Do you feel pain somewhere? - Answer: upper gum", "value": 0, "type": "M"},
  {"code": "E_55_V_92", "question": "Do you feel pain somewhere? - Answer: knee(R)", "value": -1, "type": "M"},
  {"code": "E_55_V_93", "question": "Do you feel pain somewhere? - Answer: knee(L)", "value": -1, "type": "M"},
  {"code": "E_55_V_94", "question": "Do you feel pain somewhere? - Answer: glans", "value": 0, "type": "M"},
  {"code": "E_55_V_95", "question": "Do you feel pain somewhere? - Answer: labia majora(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_96", "question": "Do you feel pain somewhere? - Answer: labia majora(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_97", "question": "Do you feel pain somewhere? - Answer: big toe(R)", "value": 0, "type": "M"},
  {"code": "E_55_V_98", "question": "Do you feel pain somewhere? - Answer: big toe(L)", "value": 0, "type": "M"},
  {"code": "E_55_V_99", "question": "Do you feel pain somewhere? - Answer: hip(R)", "value": 0, "type": "M"},

In [ ]:
data = json.loads(response.text[8:-3].replace("\'", "\"").replace(", M\"", ", \"type\": \"M\""))

In [ ]:
LLM_data = pd.DataFrame(data)

In [ ]:
LLM_data

       code                                           question  value type
0    E_59_0          How fast did the pain appear? - Answer: 0     -1    C
1    E_59_1          How fast did the pain appear? - Answer: 1     -1    C
2    E_59_2          How fast did the pain appear? - Answer: 2     -1    C
3    E_59_3          How fast did the pain appear? - Answer: 3     -1    C
4    E_59_4          How fast did the pain appear? - Answer: 4     -1    C
..      ...                                                ...    ...  ...
967   E_195                        Do you live in the suburbs?      0    B
968   E_183                       Do you live in a rural area?      0    B
969   E_224  Do you have family members who have had lung c...      1    B
970   E_223  Are there members of your family who have been...      0    B
971     E_5             Have you ever had fluid in your lungs?      0    B

[972 rows x 4 columns]

In [ ]:
codes = LLM_data["code"].to_list()

In [ ]:
values = LLM_data["value"].to_list()

In [ ]:
vector = pd.DataFrame(columns = codes)

In [ ]:
vector = vector.T

In [ ]:
vector[0] = values

In [ ]:
vector = vector.T

Vector resulting from the given prompt

In [ ]:
vector

,E_59_0,E_59_1,E_59_2,E_59_3,E_59_4,E_59_5,E_59_6,E_59_7,E_59_8,E_59_9,...,E_200,E_199,E_121,E_120,E_142,E_195,E_183,E_224,E_223,E_5
0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
from cosine_sim_engine import Cosine_sim_classifier

In [ ]:
classifier = Cosine_sim_classifier()

In [ ]:
valid_vector = classifier.extract_features(vector)

/usr/local/lib/python3.12/dist-packages/cosine_sim_engine/classify.py:123: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_record = new_record.fillna(0)

Using the built classifier for predicting the top 5 possible diagnosis

In [ ]:
classifier.similarity(valid_vector)

                  Diagnosis    Scores
0   Possible NSTEMI / STEMI  0.000590
1        Pulmonary embolism  0.000539
2          Cluster headache  0.000539
3              Epiglottitis  0.000538
4  Spontaneous rib fracture  0.000537